// Copyright 2026 Billo. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

/** Native channel tags. Channels drive timeline colors now and comfort scaling later. */
namespace FeelTags
{
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Camera_Shake);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Camera_Motion);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Screen_Flash);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Actor_Transform);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Actor_Material);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Time_Hitstop);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Time_SlowMo);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Screen_Distortion);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Haptics);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Meta_Event);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Meta_Recipe);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Screen_Color);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Screen_Fade);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Actor_Light);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_Mix);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Spawn);

	/** What a recipe makes the player feel. Groups the recipe library and the recipe browser. */
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feeling_Impact);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feeling_Weight);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feeling_Power);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feeling_Speed);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feeling_Reward);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feeling_Danger);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feeling_Dread);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feeling_Denial);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feeling_Interface);

	/** Kinds of game a recipe suits. A recipe can carry several. */
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Genre_Action);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Genre_Shooter);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Genre_Platformer);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Genre_Horror);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Genre_UI);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Genre_Vehicle);

	// FEELKIT_PRO_BEGIN
	/** Starter events for Send Feel Event and Feel Maps. Games can use them as they are or add their own. */
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_HitLanded);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_HitReceived);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Hurt);
	FEELCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Death);
	// FEELKIT_PRO_END

	/** Roots the feeling and genre pickers list. Projects can add their own tags under them. */
	inline const TCHAR* FeelingRoot = TEXT("Feel.Feeling");
	inline const TCHAR* GenreRoot = TEXT("Feel.Genre");
}
