"""Writes the generated reference chapters of the FeelKit Manual from the plugin source.

Reads the public headers, the step constructors and a few .cpp functions of the plugin, adds the
hand-written notes from src/notes/ and the hand-kept values in overrides.yaml, and writes:

    src/16_steps.generated.md
    src/17_nodes.generated.md
    src/18_settings.generated.md
    src/19_console.generated.md

Run it again after every plugin change and before every release:

    python gen_reference.py
    python gen_reference.py --plugin D:/Some/Other/FeelKit

Nothing in the plugin is changed. Internal requirement, decision and issue codes found in the
source comments are removed; the run stops if one would still reach the manual.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
SRC = Path("B:/NewUE5Project/Docs/Manual/src")
NOTES = SRC / "notes"
DEFAULT_PLUGIN = Path("B:/NewUE5Project/GameFeelDev/Plugins/FeelKit")

GENERATED_MARK = "<!-- Generated by gen_reference.py. Edit src/notes/ or overrides.yaml instead of this file. -->"

CODE = r"[A-Z]{1,4}-\d{3}"
CODE_RE = re.compile(r"\b(?:[A-Z]{1,4}-\d{3}|[DI]-0\d\d)\b")
PAREN_CODES_RE = re.compile(r"\s*\(\s*" + CODE + r"(?:\s*(?:,|and|to)\s*" + CODE + r")*\s*\)")
LEADING_CODE_RE = re.compile(r"^\s*" + CODE + r"\s*:\s*")

# The manual uses American spelling, like the plugin and Unreal (user decision 2026-09-25), so tooltips are used as written.
US_TO_UK: list[tuple[str, str]] = []

UNITS = {"Hertz": "Hz", "Centimeters": "cm", "Degrees": "°", "Seconds": "s"}

ARTICLES = ["In", "As", "To", "Or", "At", "On", "If", "Be", "By", "The", "For", "And", "With", "When", "From"]


def display_name(name: str, is_bool: bool = False) -> str:
    """Same result as the engine's FName::NameToDisplayString, which the editor uses for labels."""
    chars = name
    out: list[str] = []
    in_run = was_space = was_paren = was_number = was_minus = False
    for idx, ch in enumerate(chars):
        lower, upper, digit = ch.islower(), ch.isupper(), ch.isdigit()
        if idx == 0 and is_bool and ch == "b" and len(chars) > 1 and chars[1].isupper():
            continue
        if (upper or (digit and not was_minus)) and not in_run and not was_paren and not was_number:
            if not was_space and out:
                out.append(" ")
                was_space = True
            in_run = True
        if lower:
            in_run = False
        if ch == "_":
            ch = " "
            in_run = True
        if not out:
            ch = ch.upper()
        elif not digit and (was_space or was_paren):
            is_article = False
            for article in ARTICLES:
                length = len(article)
                if idx + length < len(chars) and not chars[idx + length].islower():
                    if chars[idx:idx + length] == article:
                        is_article = True
                        break
            ch = ch.lower() if is_article else ch.upper()
        was_space = ch == " "
        was_paren = ch == "("
        was_minus = ch == "-"
        was_number = digit or (was_number and (was_minus or ch == "."))
        out.append(ch)
    return "".join(out)


# ---------------------------------------------------------------------------------------------
# Text cleaning
# ---------------------------------------------------------------------------------------------

class CodeLeak(Exception):
    pass


def clean_text(text: str, where: str = "") -> str:
    """Prepares a source comment for the manual: no internal codes, the real settings path."""
    text = PAREN_CODES_RE.sub("", text)
    text = LEADING_CODE_RE.sub("", text)
    text = re.sub(r"\(\s*\)", "", text)
    text = text.replace("Project Settings > FeelKit >", "Project Settings > Plugins > FeelKit >")
    text = text.replace("Project Settings > FeelKit)", "Project Settings > Plugins > FeelKit)")
    text = re.sub(r"\be\.g\.\s*", "for example ", text)
    for us, uk in US_TO_UK:
        text = re.sub(r"\b" + us + r"\b", uk, text)
    text = re.sub(r"[ \t]+", " ", text).strip()
    text = re.sub(r"\s+([.,;:])(?=\s|$)", r"\1", text)
    if CODE_RE.search(text):
        raise CodeLeak(f"internal code left in text from {where}: {text}")
    return text


def sentence(text: str) -> str:
    text = text.strip()
    if text and text[-1] not in ".!?:":
        text += "."
    return text


# ---------------------------------------------------------------------------------------------
# C++ scanning
# ---------------------------------------------------------------------------------------------

def strip_line_comments(src: str) -> str:
    out = []
    i, n = 0, len(src)
    while i < n:
        c = src[i]
        if c == '"':
            j = i + 1
            while j < n and src[j] != '"':
                j += 2 if src[j] == "\\" else 1
            out.append(src[i:j + 1])
            i = j + 1
            continue
        if c == "'":
            j = i + 1
            while j < n and src[j] != "'":
                j += 2 if src[j] == "\\" else 1
            out.append(src[i:j + 1])
            i = j + 1
            continue
        if src.startswith("/*", i):
            j = src.find("*/", i + 2)
            j = n if j == -1 else j + 2
            out.append(src[i:j])
            i = j
            continue
        if src.startswith("//", i):
            j = src.find("\n", i)
            i = n if j == -1 else j
            continue
        out.append(c)
        i += 1
    return "".join(out)


def skip_to_match(src: str, i: int, open_ch: str, close_ch: str) -> int:
    """i points at open_ch; returns the index just past the matching close_ch."""
    depth = 0
    n = len(src)
    while i < n:
        c = src[i]
        if c == '"':
            i += 1
            while i < n and src[i] != '"':
                i += 2 if src[i] == "\\" else 1
        elif src.startswith("/*", i):
            i = src.find("*/", i + 2) + 1
        elif c == open_ch:
            depth += 1
        elif c == close_ch:
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    raise ValueError("unbalanced " + open_ch)


def split_top(text: str, sep: str = ",") -> list[str]:
    parts, depth, cur, i = [], 0, [], 0
    while i < len(text):
        c = text[i]
        if c == '"':
            j = i + 1
            while j < len(text) and text[j] != '"':
                j += 2 if text[j] == "\\" else 1
            cur.append(text[i:j + 1])
            i = j + 1
            continue
        if c in "(<{[":
            depth += 1
        elif c in ")>}]":
            depth -= 1
        if c == sep and depth == 0:
            parts.append("".join(cur).strip())
            cur = []
        else:
            cur.append(c)
        i += 1
    if "".join(cur).strip():
        parts.append("".join(cur).strip())
    return parts


def find_top(text: str, chars: str, start: int = 0) -> int:
    depth, i = 0, start
    while i < len(text):
        c = text[i]
        if c == '"':
            i += 1
            while i < len(text) and text[i] != '"':
                i += 2 if text[i] == "\\" else 1
        elif text.startswith("/*", i):
            i = text.find("*/", i + 2) + 1
        elif c in "(<[":
            depth += 1
        elif c in ")>]":
            depth -= 1
        elif c in chars and depth == 0:
            return i
        i += 1
    return -1


def parse_specifiers(args: str) -> tuple[list[str], dict[str, str]]:
    flags, meta = [], {}
    for part in split_top(args):
        if not part:
            continue
        if "=" in part:
            key, value = part.split("=", 1)
            key, value = key.strip(), value.strip()
            if key.lower() == "meta":
                inner = value.strip()
                if inner.startswith("("):
                    inner = inner[1:-1]
                for m in split_top(inner):
                    if "=" in m:
                        mk, mv = m.split("=", 1)
                        meta[mk.strip()] = mv.strip().strip('"')
                    elif m:
                        meta[m.strip()] = ""
            else:
                meta["__" + key] = value.strip('"')
        else:
            flags.append(part.strip())
    return flags, meta


def doc_before(src: str, pos: int) -> str:
    j = pos
    while j > 0 and src[j - 1] in " \t\r\n":
        j -= 1
    if not src[:j].endswith("*/"):
        return ""
    start = src.rfind("/**", 0, j)
    if start == -1:
        return ""
    between = src[start:j]
    if between.count("*/") != 1:
        return ""
    return between[3:-2]


def doc_lines(raw: str) -> list[str]:
    lines = []
    for line in raw.split("\n"):
        line = line.strip()
        if line.startswith("*"):
            line = line[1:]
        lines.append(line.rstrip())
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return lines


@dataclass
class Doc:
    summary: list[str] = field(default_factory=list)  # Markdown blocks: paragraphs and "- " items
    params: dict[str, str] = field(default_factory=dict)
    returns: str = ""

    def text(self) -> str:
        return " ".join(b[2:] if b.startswith("- ") else b for b in self.summary)


def parse_doc(raw: str, where: str) -> Doc:
    doc = Doc()
    current: list[str] = []
    target = None  # ("param", name) or ("return",)
    blocks: list[str] = []

    def flush():
        nonlocal current, target
        text = " ".join(s.strip() for s in current if s.strip())
        if text:
            if target is None:
                blocks.append(text)
            elif target[0] == "param":
                doc.params[target[1]] = clean_text(text, where)
            else:
                doc.returns = clean_text(text, where)
        current = []

    for line in doc_lines(raw):
        stripped = line.strip()
        if stripped.startswith("@param"):
            flush()
            m = re.match(r"@param\s+(\w+)\s*(.*)", stripped)
            target = ("param", m.group(1))
            current = [m.group(2)]
        elif stripped.startswith("@return"):
            flush()
            target = ("return",)
            current = [stripped[len("@return"):]]
        elif target is None and stripped.startswith("- "):
            flush()
            blocks.append("- " + stripped[2:])
        elif target is None and not stripped:
            flush()
        else:
            current.append(stripped)
    flush()
    doc.summary = [("- " + clean_text(b[2:], where)) if b.startswith("- ") else clean_text(b, where) for b in blocks]
    return doc


@dataclass
class Prop:
    name: str
    type: str
    default: str | None
    flags: list[str]
    meta: dict[str, str]
    doc: Doc
    owner: str
    editor_only: bool = False

    @property
    def category(self) -> str:
        return self.meta.get("__Category", "")

    @property
    def is_bool(self) -> bool:
        return self.type.strip() == "bool"

    @property
    def label(self) -> str:
        return self.meta.get("DisplayName") or display_name(self.name, self.is_bool)

    @property
    def editable(self) -> bool:
        return any(f in self.flags for f in ("EditAnywhere", "EditDefaultsOnly", "EditInstanceOnly", "VisibleAnywhere"))


@dataclass
class Param:
    name: str
    type: str
    default: str | None
    meta: dict[str, str]

    @property
    def is_out(self) -> bool:
        t = self.type
        return "&" in t and not t.strip().startswith("const") and "UPARAM(ref)" not in t

    @property
    def is_bool(self) -> bool:
        return self.type.replace("const", "").strip() == "bool"


@dataclass
class Func:
    name: str
    ret: str
    params: list[Param]
    flags: list[str]
    meta: dict[str, str]
    doc: Doc
    owner: str
    static: bool

    @property
    def label(self) -> str:
        return self.meta.get("DisplayName") or display_name(self.name)


@dataclass
class EnumValue:
    name: str
    label: str
    doc: str


@dataclass
class TypeDecl:
    kind: str
    name: str
    base: str
    flags: list[str]
    meta: dict[str, str]
    doc: Doc
    file: Path
    body: str
    props: list[Prop] = field(default_factory=list)
    funcs: list[Func] = field(default_factory=list)
    values: list[EnumValue] = field(default_factory=list)
    inline: dict[str, str] = field(default_factory=dict)
    ctor: dict[str, str] = field(default_factory=dict)

    @property
    def label(self) -> str:
        return self.meta.get("DisplayName") or display_name(self.name[1:])


def preprocessor_ranges(src: str) -> list[tuple[int, int, str]]:
    ranges, stack = [], []
    for m in re.finditer(r"^[ \t]*#(if|ifdef|ifndef|else|elif|endif)\b(.*)$", src, re.M):
        kind, cond = m.group(1), m.group(2).strip()
        if kind.startswith("if"):
            stack.append((m.end(), cond))
        elif kind in ("else", "elif"):
            if stack:
                start, c = stack.pop()
                ranges.append((start, m.start(), c))
                stack.append((m.end(), "!" + c))
        elif stack:
            start, c = stack.pop()
            ranges.append((start, m.start(), c))
    return ranges


def in_condition(ranges, pos: int, name: str) -> bool:
    return any(s <= pos < e and c == name for s, e, c in ranges)


def parse_decl_name(decl: str) -> tuple[str, str, str | None]:
    eq = find_top(decl, "=")
    default = None
    if eq != -1:
        default = decl[eq + 1:].strip()
        decl = decl[:eq]
    decl = decl.strip()
    m = re.match(r"^(.*?)(\w+)\s*$", decl, re.S)
    return m.group(1).strip(), m.group(2), default


def parse_members(td: TypeDecl, src: str, body_start: int, ranges) -> None:
    body = td.body
    for m in re.finditer(r"\b(UPROPERTY|UFUNCTION)\s*\(", body):
        kind = m.group(1)
        open_at = m.end() - 1
        close_at = skip_to_match(body, open_at, "(", ")")
        flags, meta = parse_specifiers(body[open_at + 1:close_at - 1])
        where = f"{td.name} {body[close_at:close_at + 60].strip()[:40]}"
        doc = parse_doc(doc_before(body, m.start()), where)
        editor_only = in_condition(ranges, body_start + m.start(), "WITH_EDITORONLY_DATA")
        if kind == "UPROPERTY":
            end = find_top(body, ";", close_at)
            ptype, name, default = parse_decl_name(body[close_at:end])
            td.props.append(Prop(name, ptype, default, flags, meta, doc, td.name, editor_only))
        else:
            end = find_top(body, ";{", close_at)
            decl = body[close_at:end].strip()
            paren = decl.index("(")
            head = decl[:paren]
            pclose = skip_to_match(decl, paren, "(", ")")
            args = decl[paren + 1:pclose - 1]
            hm = re.match(r"^(.*?)(\w+)\s*$", head, re.S)
            ret = hm.group(1).replace("virtual", "").strip()
            static = "static" in ret.split()
            ret = ret.replace("static", "").strip()
            params = []
            for a in split_top(args):
                if not a:
                    continue
                pmeta = {}
                um = re.match(r"\s*UPARAM\s*\(", a)
                if um:
                    uclose = skip_to_match(a, um.end() - 1, "(", ")")
                    _, pmeta = parse_specifiers(a[um.end():uclose - 1])
                    if "UPARAM(ref)" in a[:uclose]:
                        pmeta["ref"] = "1"
                    a = a[uclose:]
                ptype, pname, pdefault = parse_decl_name(a)
                params.append(Param(pname, ptype, pdefault, pmeta))
            td.funcs.append(Func(hm.group(2), ret, params, flags, meta, doc, td.name, static))
    for m in re.finditer(r"virtual\s+bool\s+(\w+)\(\)\s*const\s*override\s*\{\s*return\s+(true|false)\s*;\s*\}", body):
        td.inline[m.group(1)] = m.group(2)


def parse_enum_body(td: TypeDecl) -> None:
    pattern = re.compile(r"(?:/\*\*(?P<doc>.*?)\*/\s*)?(?P<name>[A-Za-z_]\w*)\s*(?:=\s*[^,]+?)?\s*(?:UMETA\s*\((?P<umeta>[^)]*)\))?\s*(?:,|\Z)", re.S)
    for m in pattern.finditer(td.body.strip()):
        name = m.group("name")
        label = None
        if m.group("umeta"):
            _, meta = parse_specifiers(m.group("umeta"))
            label = meta.get("__DisplayName")
            if meta.get("Hidden") is not None:
                continue
        doc = clean_text(" ".join(l.strip() for l in doc_lines(m.group("doc") or "") if l.strip()), td.name + "." + name)
        td.values.append(EnumValue(name, label or display_name(name), doc))


def read_source(path: Path) -> str:
    """A source file as FeelKit Pro ships it: the edition marker lines (Tools/Run/make_edition.py) are left out."""
    lines = path.read_text(encoding="utf-8-sig").split("\n")
    return "\n".join(l for l in lines if l.strip() not in ("// FEELKIT_PRO_BEGIN", "// FEELKIT_PRO_END")
                     and not l.strip().startswith("// FEELKIT_LITE:"))


def parse_header(path: Path, types: dict[str, TypeDecl]) -> None:
    raw = read_source(path)
    src = strip_line_comments(raw)
    ranges = preprocessor_ranges(src)
    for m in re.finditer(r"\b(UCLASS|USTRUCT|UENUM|UINTERFACE)\s*\(", src):
        # Skip mentions inside comments.
        line_start = src.rfind("\n", 0, m.start()) + 1
        if src[line_start:m.start()].strip():
            continue
        open_at = m.end() - 1
        close_at = skip_to_match(src, open_at, "(", ")")
        flags, meta = parse_specifiers(src[open_at + 1:close_at - 1])
        dm = re.compile(r"\s*(class|struct|enum\s+class)\s+(?:\w+_API\s+)?(\w+)\s*(?::\s*(?:public\s+)?([\w:]+))?\s*\{", re.S).match(src, close_at)
        if not dm:
            continue
        brace = dm.end() - 1
        body_end = skip_to_match(src, brace, "{", "}")
        kind = {"UCLASS": "class", "USTRUCT": "struct", "UENUM": "enum", "UINTERFACE": "interface"}[m.group(1)]
        name = dm.group(2)
        td = TypeDecl(kind, name, dm.group(3) or "", flags, meta, parse_doc(doc_before(src, m.start()), name), path, src[brace + 1:body_end - 1])
        if kind == "enum":
            parse_enum_body(td)
        else:
            parse_members(td, src, brace + 1, ranges)
        types[name] = td
        if kind == "interface":
            im = re.compile(r"class\s+(?:\w+_API\s+)?(I" + name[1:] + r")\s*\{").search(src, body_end)
            if im:
                ib = im.end() - 1
                iend = skip_to_match(src, ib, "{", "}")
                itd = TypeDecl("iinterface", im.group(1), "", [], {}, td.doc, path, src[ib + 1:iend - 1])
                parse_members(itd, src, ib + 1, ranges)
                types[itd.name] = itd


# ---------------------------------------------------------------------------------------------
# .cpp facts
# ---------------------------------------------------------------------------------------------

@dataclass
class CppFacts:
    channels: dict[str, str] = field(default_factory=dict)       # class -> FeelTags symbol
    preview: dict[str, str] = field(default_factory=dict)        # class -> "true"/"false"
    ctors: dict[str, dict[str, str]] = field(default_factory=dict)
    validation: dict[str, list[tuple[str, str]]] = field(default_factory=dict)
    tags: dict[str, tuple[str, str]] = field(default_factory=dict)  # symbol -> (tag, comment)
    cvars: list[tuple[str, str, str, str]] = field(default_factory=list)
    stats: list[tuple[str, str]] = field(default_factory=list)
    showdebug_category: str = ""
    delegates: dict[str, list[tuple[str, str]]] = field(default_factory=dict)


def function_bodies(src: str, name: str):
    for m in re.finditer(r"(\w+)::" + name + r"\s*\(([^)]*)\)\s*(?:const)?\s*(?::[^{;]*)?\{", src):
        start = m.end() - 1
        end = skip_to_match(src, start, "{", "}")
        yield m.group(1), src[start + 1:end - 1]


def parse_cpp(path: Path, facts: CppFacts) -> None:
    src = strip_line_comments(read_source(path))
    for cls, body in function_bodies(src, "GetDefaultChannel_Implementation"):
        found = re.findall(r"return\s+FeelTags::(\w+)", body)
        if found:
            facts.channels[cls] = found[-1]
    for cls, body in function_bodies(src, "SupportsPreview_Implementation"):
        m = re.search(r"return\s+(true|false)\s*;", body)
        if m:
            facts.preview[cls] = m.group(1)
    for m in re.finditer(r"(\w+)::\1\s*\(\s*\)\s*(?::[^{;]*)?\{", src):
        start = m.end() - 1
        body = src[start + 1:skip_to_match(src, start, "{", "}") - 1]
        values = facts.ctors.setdefault(m.group(1), {})
        for statement in split_top(body, ";"):
            statement = statement.strip()
            sm = re.match(r"^([\w\.]+)\s*=\s*(.+)$", statement, re.S)
            if sm:
                values[sm.group(1)] = sm.group(2).strip()
            elif re.match(r"^\w+\.AddDefaulted\(\)$", statement):
                values[statement.split(".")[0] + ".__AddDefaulted"] = "1"
    for cls, body in function_bodies(src, "ValidateStep"):
        for vm in re.finditer(r"Out(Errors|Warnings)\.Add\(NSLOCTEXT\(\s*\"[^\"]*\"\s*,\s*\"[^\"]*\"\s*,\s*\"((?:[^\"\\]|\\.)*)\"\s*\)\)", body):
            facts.validation.setdefault(cls, []).append(("Error" if vm.group(1) == "Errors" else "Warning", vm.group(2)))
    for tm in re.finditer(r"UE_DEFINE_GAMEPLAY_TAG_COMMENT\(\s*(\w+)\s*,\s*\"([^\"]+)\"\s*,\s*\"((?:[^\"\\]|\\.)*)\"\s*\)", src):
        facts.tags[tm.group(1)] = (tm.group(2), tm.group(3))
    for cm in re.finditer(r"TAutoConsoleVariable<(\w+)>\s+\w+\(\s*TEXT\(\"([^\"]+)\"\)\s*,\s*([^,]+?)\s*,\s*TEXT\(\"((?:[^\"\\]|\\.)*)\"\)", src):
        facts.cvars.append((cm.group(2), cm.group(1), cm.group(3), cm.group(4)))
    for sm in re.finditer(r"DECLARE_(CYCLE_STAT|DWORD_ACCUMULATOR_STAT|STATS_GROUP)\(\s*TEXT\(\"([^\"]+)\"\)", src):
        facts.stats.append((sm.group(1), sm.group(2)))
    dm = re.search(r"static const FName FeelCategory\(TEXT\(\"(\w+)\"\)\)", src)
    if dm:
        facts.showdebug_category = dm.group(1)


def parse_delegates(path: Path, facts: CppFacts) -> None:
    src = strip_line_comments(read_source(path))
    for m in re.finditer(r"DECLARE_(?:DYNAMIC_)?MULTICAST_DELEGATE_\w+\(\s*(\w+)\s*,([^;]*)\);", src):
        parts = [p.strip() for p in split_top(m.group(2))]
        params = []
        if "/*" in m.group(2):
            # Native delegates give only types, with the names in comments.
            for p in parts:
                nm = re.search(r"/\*\s*(\w+)\s*\*/", p)
                params.append((re.sub(r"/\*.*?\*/", "", p).strip(), nm.group(1) if nm else ""))
        else:
            for i in range(0, len(parts) - 1, 2):
                params.append((parts[i], parts[i + 1]))
        facts.delegates[m.group(1)] = params


# ---------------------------------------------------------------------------------------------
# Formatting
# ---------------------------------------------------------------------------------------------

class Reference:
    def __init__(self, plugin: Path, overrides: dict):
        self.plugin = plugin
        self.ov = overrides
        self.types: dict[str, TypeDecl] = {}
        self.facts = CppFacts()
        self.notes: dict[str, str] = {}
        self.warnings: list[str] = []
        self.unassigned_editions: list[str] = []

    # --- loading ---------------------------------------------------------------------------

    def load(self) -> None:
        headers, cpps = [], []
        for base in [self.plugin / "Source", self.plugin / "Extras"]:
            for p in base.rglob("*.h"):
                if "Tests" in p.parts or "Intermediate" in p.parts:
                    continue
                if "Public" in p.parts or p.name in ("FeelEditorSettings.h", "FeelEditorScripting.h"):
                    headers.append(p)
            for p in base.rglob("*.cpp"):
                if "Tests" in p.parts or "Intermediate" in p.parts:
                    continue
                cpps.append(p)
        for h in sorted(headers):
            parse_header(h, self.types)
            parse_delegates(h, self.facts)
        for c in sorted(cpps):
            parse_cpp(c, self.facts)
        for name, td in self.types.items():
            td.ctor = self.facts.ctors.get(name, {})
        for f in sorted(NOTES.glob("*.md")):
            self.load_notes(f)

    def load_notes(self, path: Path) -> None:
        key, lines = None, []
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith("@@ "):
                if key:
                    self.notes[key] = "\n".join(lines).strip()
                key, lines = line[3:].strip(), []
            elif key:
                lines.append(line)
        if key:
            self.notes[key] = "\n".join(lines).strip()

    def note(self, key: str) -> str:
        text = self.notes.get(key, "")
        return text

    # --- type helpers ----------------------------------------------------------------------

    def chain(self, name: str) -> list[TypeDecl]:
        out = []
        while name in self.types:
            td = self.types[name]
            out.append(td)
            name = td.base
        return out

    def is_a(self, name: str, base: str) -> bool:
        return any(td.name == base for td in self.chain(name))

    def all_props(self, name: str) -> list[Prop]:
        props = []
        for td in reversed(self.chain(name)):
            props.extend(td.props)
        return props

    def ctor_value(self, cls: str, prop: str) -> str | None:
        for td in self.chain(cls):
            if prop in td.ctor:
                return td.ctor[prop]
        return None

    def inline_or_cpp(self, cls: str, func: str, default: str) -> str:
        for td in self.chain(cls):
            if func in td.inline:
                return td.inline[func]
            if func == "SupportsPreview_Implementation" and td.name in self.facts.preview:
                return self.facts.preview[td.name]
        return default

    def channel_of(self, cls: str) -> str:
        for td in self.chain(cls):
            if td.name in self.facts.channels:
                return self.facts.tags[self.facts.channels[td.name]][0]
        return ""

    def comfort_group_of(self, tag: str) -> str:
        mapping = self.default_channel_groups()
        best, best_len = None, -1
        for channel, group in mapping:
            if tag == channel or tag.startswith(channel + "."):
                if len(channel) > best_len:
                    best, best_len = group, len(channel)
        return best or ""

    def default_channel_groups(self) -> list[tuple[str, str]]:
        raw = self.types["UFeelSettings"].ctor.get("ChannelComfortGroups", "")
        enum = self.types["EFeelComfortGroup"]
        out = []
        for m in re.finditer(r"FFeelChannelComfortMapping\(\s*FeelTags::(\w+)\s*,\s*EFeelComfortGroup::(\w+)\s*\)", raw):
            out.append((self.facts.tags[m.group(1)][0], self.enum_label(enum, m.group(2))))
        return out

    def enum_label(self, enum: TypeDecl, value: str) -> str:
        for v in enum.values:
            if v.name == value:
                return v.label
        return display_name(value)

    def edition(self, key: str) -> str:
        lite = set(self.ov.get("lite", []))
        if key in lite:
            return "Lite and Pro"
        if key not in set(self.ov.get("pro", [])) and key not in set(self.ov.get("step_order", [])):
            self.unassigned_editions.append(key)
        return "Pro"

    # --- values ------------------------------------------------------------------------------

    @staticmethod
    def number(text: str) -> str | None:
        t = text.strip()
        t = re.sub(r"(?<=\d)[fF]$", "", t)
        try:
            v = float(t)
        except ValueError:
            return None
        if v == int(v) and abs(v) < 1e12:
            return str(int(v))
        return "%g" % v

    def numbers_in(self, text: str) -> list[str]:
        inner = text[text.index("(") + 1:text.rindex(")")]
        return [self.number(x) or x for x in split_top(inner)]

    def format_value(self, ptype: str, raw: str | None, owner: str = "", pname: str = "") -> str:
        key = f"{owner}.{pname}"
        if key in self.ov.get("defaults", {}):
            return self.ov["defaults"][key]
        t = re.sub(r"\bconst\b|&", "", ptype).strip()
        base = t.rstrip("*").strip()
        if raw is not None:
            raw = raw.strip()
        if t == "bool":
            return "On" if raw == "true" else "Off"
        if t in ("float", "double", "int32", "uint8", "int64"):
            if raw is None:
                return "0"
            return self.number(raw) or raw
        if base in self.types and self.types[base].kind == "enum":
            enum = self.types[base]
            if raw is None:
                return enum.values[0].label if enum.values else ""
            return self.enum_label(enum, raw.split("::")[-1])
        if base == "ETriggerEvent" and raw:
            return display_name(raw.split("::")[-1])
        if base in ("FVector", "FVector2D"):
            if raw is None or raw.endswith("ZeroVector"):
                return "(0, 0, 0)" if base == "FVector" else "(0, 0)"
            if raw.endswith("OneVector"):
                return "(1, 1, 1)"
            if raw.endswith("UpVector"):
                return "(0, 0, 1)"
            return "(" + ", ".join(self.numbers_in(raw)) + ")"
        if base == "FRotator":
            if raw is None or "ZeroRotator" in raw:
                return "Pitch 0, Yaw 0, Roll 0"
            p, y, r = self.numbers_in(raw)
            return f"Pitch {p}, Yaw {y}, Roll {r}"
        if base == "FLinearColor":
            if raw is None:
                return "R 0, G 0, B 0, A 0"
            if raw.endswith("::White"):
                return "White (R 1, G 1, B 1)"
            if raw.endswith("::Black"):
                return "Black (R 0, G 0, B 0)"
            nums = self.numbers_in(raw)
            text = f"R {nums[0]}, G {nums[1]}, B {nums[2]}"
            if len(nums) > 3 and nums[3] != "1":
                text += f", A {nums[3]}"
            return text
        if base == "FFloatInterval" and raw:
            lo, hi = self.numbers_in(raw)
            return f"Min {lo}, Max {hi}"
        if base in ("FName",):
            if raw is None or raw in ("NAME_None", "FName()"):
                return "None"
            m = re.search(r'"(.*)"', raw)
            return f"`{m.group(1)}`" if m else raw
        if base in ("FString",):
            if raw is None:
                return "empty"
            m = re.search(r'"(.*)"', raw)
            return f"`{m.group(1)}`" if m else raw
        if base == "FText":
            if raw is None:
                return "empty"
            m = re.search(r'LOCTEXT\(\s*"[^"]*"\s*,\s*"((?:[^"\\]|\\.)*)"\s*\)', raw)
            return f'"{m.group(1)}"' if m else raw
        if base == "FGameplayTag":
            return "None"
        if base == "FGameplayTagContainer":
            return "empty"
        if re.match(r"^(TArray|TMap|TSet)<", base):
            return "empty"
        if re.match(r"^(TObjectPtr|TSoftObjectPtr|TSoftClassPtr|TSubclassOf|TWeakObjectPtr|TScriptInterface)<", base) or base in ("FSoftObjectPath",) or t.endswith("*"):
            return "None"
        if base in self.types and self.types[base].kind == "struct":
            return "see below"
        if raw is not None:
            return raw
        self.warnings.append(f"no default format for {owner}.{pname} ({ptype})")
        return ""

    def units(self, prop: Prop, owner: str) -> str:
        key = f"{owner}.{prop.name}"
        extra = self.ov.get("units", {})
        if key in extra:
            return extra[key]
        if f"{prop.owner}.{prop.name}" in extra:
            return extra[f"{prop.owner}.{prop.name}"]
        return UNITS.get(prop.meta.get("Units", ""), "")

    def with_units(self, value: str, unit: str) -> str:
        if not unit or value in ("", "None", "empty"):
            return value
        if unit in ("°", "°/s"):
            if re.match(r"^-?[\d.]+$", value):
                return value + unit
            return value + " (degrees)"
        return f"{value} {unit}"

    def prop_default(self, prop: Prop, owner: str) -> str:
        raw = self.ctor_value(owner, prop.name)
        if raw is None:
            raw = prop.default
        key = f"{owner}.{prop.name}"
        if key in self.ov.get("defaults", {}):
            return self.ov["defaults"][key]
        value = self.format_value(prop.type, raw, prop.owner, prop.name)
        return self.with_units(value, self.units(prop, owner))

    def condition_text(self, prop: Prop, siblings: list[Prop]) -> str:
        cond = prop.meta.get("EditCondition")
        if not cond:
            return ""
        by_name = {p.name: p for p in siblings}
        parts = []
        for clause in re.split(r"\s*&&\s*", cond):
            clause = clause.strip()
            m = re.match(r"^(!?)(\w+)$", clause)
            if m:
                p = by_name.get(m.group(2))
                label = p.label if p else display_name(m.group(2), True)
                parts.append(f"**{label}** is {'off' if m.group(1) else 'on'}")
                continue
            m = re.match(r"^(\w+)\s*(==|!=|>|<|>=|<=)\s*(.+)$", clause)
            if not m:
                self.warnings.append(f"edit condition not translated: {cond}")
                return ""
            p = by_name.get(m.group(1))
            label = p.label if p else display_name(m.group(1))
            rhs = m.group(3).strip()
            if rhs == "nullptr":
                value = "empty"
                op = {"==": "is", "!=": "is not"}[m.group(2)]
                parts.append(f"**{label}** {op} {value}")
                continue
            if "::" in rhs:
                enum_name, value_name = rhs.split("::")
                enum = self.types.get(enum_name)
                value = self.enum_label(enum, value_name) if enum else display_name(value_name)
                value = f"**{value}**"
            else:
                value = self.number(rhs) or rhs
            op = {"==": "is", "!=": "is not", ">": "is above", "<": "is below", ">=": "is at least", "<=": "is at most"}[m.group(2)]
            parts.append(f"**{label}** {op} {value}")
        verb = "Shown only when" if "EditConditionHides" in prop.meta else "Editable only when"
        return f"{verb} " + " and ".join(parts) + "."

    def range_text(self, prop: Prop) -> str:
        lo, hi = prop.meta.get("ClampMin"), prop.meta.get("ClampMax")
        lo = self.number(lo) if lo else None
        hi = self.number(hi) if hi else None
        if lo is not None and hi is not None:
            return f"Range {lo} to {hi}."
        if lo is not None:
            return f"At least {lo}."
        if hi is not None:
            return f"At most {hi}."
        return ""

    def prop_description(self, prop: Prop, owner: str, siblings: list[Prop]) -> str:
        key = f"{owner}.{prop.name}"
        text = " ".join(b[2:] if b.startswith("- ") else b for b in prop.doc.summary)
        text = self.ov.get("descriptions", {}).get(key, self.ov.get("descriptions", {}).get(f"{prop.owner}.{prop.name}", text))
        text = sentence(text) if text else ""
        extra = [self.range_text(prop), self.condition_text(prop, siblings)]
        if "VisibleAnywhere" in prop.flags:
            extra.append("Read only.")
        if prop.editor_only:
            extra.append("Editor only: not included in packaged games.")
        if "AdvancedDisplay" in prop.flags:
            extra.append("Under the advanced arrow of its category.")
        if prop.editor_only:
            text = text.replace(" Not included in cooked builds.", "")
        lead = "**Pro.**" if f"{prop.owner}.{prop.name}" in set(self.ov.get("pro_fields", [])) else ""
        text = " ".join(x for x in [lead, text] + extra if x)
        return text

    # --- Markdown building blocks -----------------------------------------------------------

    @staticmethod
    def cell(text: str) -> str:
        return text.replace("|", "\\|").replace("\n", " ")

    def prop_rows(self, props: list[Prop], owner: str, siblings: list[Prop] | None = None, prefix: str = "") -> list[list[str]]:
        rows = []
        siblings = siblings if siblings is not None else props
        for p in props:
            rows.append([f"**{prefix}{p.label}**", self.prop_default(p, owner), self.prop_description(p, owner, siblings)])
        return rows

    def table(self, header: list[str], rows: list[list[str]], widths: list[int] | None = None) -> str:
        lines = []
        if widths:
            lines.append("{widths: " + ",".join(str(w) for w in widths) + "}")
        lines.append("| " + " | ".join(header) + " |")
        lines.append("|" + "|".join("---" for _ in header) + "|")
        for r in rows:
            lines.append("| " + " | ".join(self.cell(c) for c in r) + " |")
        return "\n".join(lines)

    def editable_props(self, cls: str, skip: set[str] | None = None, own_only: bool = False) -> list[Prop]:
        skip = skip or set()
        hidden = set(self.ov.get("hidden", []))
        props = self.types[cls].props if own_only else self.all_props(cls)
        return [p for p in props if p.editable and p.name not in skip and f"{p.owner}.{p.name}" not in hidden
                and "BlueprintAssignable" not in p.flags]

    def prop_table(self, cls: str, props: list[Prop], owner: str | None = None) -> str:
        owner = owner or cls
        categories = []
        for p in props:
            if p.category not in categories:
                categories.append(p.category)
        rows = []
        for cat in categories:
            group = [p for p in props if p.category == cat]
            if len(categories) > 1:
                rows.append([">> " + (cat.replace("|", " > ") or "Other"), "", ""])
            rows.extend(self.prop_rows(group, owner, props))
        return self.table(["Property", "Default", "Description"], rows, [26, 20, 54])

    def struct_tables(self, props: list[Prop], owner: str) -> list[str]:
        """Sub-tables for array and struct properties whose element type is a FeelKit struct."""
        out = []
        for p in props:
            m = re.match(r"^TArray<\s*(F\w+)\s*>$", p.type.strip())
            inner = m.group(1) if m else None
            if not inner and p.type.strip() in self.types and self.types[p.type.strip()].kind == "struct":
                inner = p.type.strip()
            if not inner or inner not in self.types or f"{owner}.{p.name}" in set(self.ov.get("no_subtable", [])):
                continue
            sub = self.editable_props(inner)
            if not sub:
                continue
            what = "Each entry of" if m else "The fields of"
            out.append(f"{what} **{p.label}**:")
            out.append(self.table(["Field", "Default", "Description"], self.prop_rows(sub, inner), [26, 20, 54]))
        return out

    # --- function nodes -----------------------------------------------------------------------

    def pin_type(self, t: str) -> str:
        t = re.sub(r"UPARAM\(.*?\)", "", t)
        t = re.sub(r"\bconst\b|&", "", t).strip()
        pointer = t.endswith("*")
        t = t.rstrip("*").strip()
        m = re.match(r"TScriptInterface<I(\w+)>", t)
        if m:
            return display_name(m.group(1)) + " (interface)"
        simple = {"float": "Float", "double": "Float", "int32": "Integer", "bool": "Boolean", "FName": "Name",
                  "FString": "String", "FText": "Text", "FVector": "Vector", "FGameplayTag": "Gameplay Tag",
                  "FGameplayTagContainer": "Gameplay Tag Container", "UObject": "Object", "AActor": "Actor"}
        if t in simple:
            return simple[t] + (" (object)" if pointer and t not in ("UObject", "AActor") else "")
        if pointer and t[:1] in "UA":
            return display_name(t[1:])
        if t[:1] in "FE":
            return display_name(t[1:])
        return t

    def pin_default(self, param: Param) -> str:
        if param.default is None:
            return ""
        return self.format_value(param.type, param.default)

    def function_block(self, fn: Func, key: str, heading_level: str = "###", anchor: str = "", owner_label: str = "", node: str = "") -> str:
        lines = [f"{heading_level} {fn.label}" + (f" {{#{anchor}}}" if anchor else ""), ""]
        lines.append(f"[edition: {self.edition(key)}]")
        lines.append("")
        lines += self.doc_blocks(fn.doc.summary)
        note = self.note(key)
        if note:
            lines += [note, ""]
        pure = "BlueprintPure" in fn.flags
        kind = "Pure node, no execution pins" if pure else "Callable node with execution pins"
        if fn.meta.get("BlueprintInternalUseOnly") == "true":
            kind = "Latent node with an output execution pin for each outcome"
        facts = [f"- **Node:** {node or kind}."]
        if owner_label:
            facts.append(f"- **Target:** {owner_label}.")
        facts.append(f"- **Category:** {fn.meta.get('__Category', '').replace('|', ' > ')}.")
        facts.append(f"- **C++:** `{fn.owner}::{fn.name}`.")
        lines += facts + [""]
        world = fn.meta.get("WorldContext")
        auto_ref = set(x.strip() for x in fn.meta.get("AutoCreateRefTerm", "").split(",") if x.strip())
        advanced = set(x.strip() for x in fn.meta.get("AdvancedDisplay", "").split(",") if x.strip())
        rows = []
        for p in fn.params:
            if p.name == world:
                continue
            desc = fn.doc.params.get(p.name, "")
            desc = sentence(desc) if desc else ""
            if p.name in auto_ref:
                desc += " Can be left unconnected."
            if p.name in advanced:
                desc += " Shown under the node's advanced arrow."
            direction = "Out" if p.is_out else "In"
            rows.append([f"**{display_name(p.name, p.is_bool)}**", direction, self.pin_type(p.type), self.pin_default(p), desc.strip()])
        if kind.startswith("latent"):
            for e in [p for p in self.types[fn.owner].props if "BlueprintAssignable" in p.flags]:
                rows.append([f"**{e.label}**", "Out", "Execution", "", sentence(e.doc.text())])
            sig = []
            for e in [p for p in self.types[fn.owner].props if "BlueprintAssignable" in p.flags][:1]:
                sig = self.facts.delegates.get(e.type.strip(), [])
            for t, n in sig:
                rows.append([f"**{display_name(n)}**", "Out", self.pin_type(t), "", "Handle of the play, set when either output fires."])
        elif fn.ret and fn.ret != "void":
            rows.append(["**Return Value**", "Out", self.pin_type(fn.ret), "", sentence(fn.doc.returns) if fn.doc.returns else ""])
        if rows:
            lines.append(self.table(["Pin", "In or out", "Type", "Default", "Description"], rows, [20, 9, 17, 11, 43]))
            lines.append("")
        return "\n".join(lines)

    @staticmethod
    def doc_blocks(blocks: list[str]) -> list[str]:
        lines = []
        for i, block in enumerate(blocks):
            lines.append(block)
            is_item = block.startswith("- ")
            next_is_item = i + 1 < len(blocks) and blocks[i + 1].startswith("- ")
            if not (is_item and next_is_item):
                lines.append("")
        return lines

    def find_func(self, cls: str, name: str) -> Func:
        for f in self.types[cls].funcs:
            if f.name == name:
                return f
        raise KeyError(f"{cls}.{name}")

    # --- chapters -----------------------------------------------------------------------------

    def step_classes(self) -> list[str]:
        order = self.ov["step_order"]
        found = [n for n, td in self.types.items() if td.kind == "class" and self.is_a(n, "UFeelStep")
                 and n != "UFeelStep" and "Abstract" not in td.flags]
        missing = sorted(set(found) - set(order))
        extra = sorted(set(order) - set(found))
        if missing or extra:
            raise SystemExit(f"step_order in overrides.yaml does not match the plugin. Missing: {missing}. Unknown: {extra}.")
        return order

    def chapter16(self) -> str:
        out = [GENERATED_MARK, "", "# Step reference {#ch16}", ""]
        out.append(self.note("chapter.16") + "\n")

        recipe = self.types["UFeelRecipe"]
        out += ["## Recipe fields {#ref_recipe_fields}", "", "[edition: Lite and Pro]", ""]
        out.append(self.note("section.recipe_fields") + "\n")
        props = self.editable_props("UFeelRecipe")
        out.append(self.prop_table("UFeelRecipe", props))
        out.append("")
        out += self.struct_tables(props, "UFeelRecipe")
        out.append("")
        mapping = self.editable_props("FFeelParameterMapping")

        out += ["## Track fields {#ref_track_fields}", "", "[edition: Lite and Pro]", ""]
        out.append(self.note("section.track_fields") + "\n")
        track_props = self.editable_props("FFeelTrack")
        cond = self.editable_props("FFeelConditions")
        rows = []
        cats = []
        for p in track_props:
            if p.category not in cats:
                cats.append(p.category)
        for cat in cats:
            rows.append([">> " + cat, "", ""])
            for p in [x for x in track_props if x.category == cat]:
                if p.type.strip() == "FFeelConditions":
                    rows.extend(self.prop_rows(cond, "FFeelConditions", cond))
                else:
                    rows.extend(self.prop_rows([p], "FFeelTrack", track_props))
        out.append(self.table(["Property", "Default", "Description"], rows, [26, 20, 54]))
        out.append("")
        out.append("Each entry of **Parameter Mappings**:")
        out.append(self.table(["Field", "Default", "Description"], self.prop_rows(mapping, "FFeelParameterMapping"), [26, 20, 54]))
        out.append("")

        out += ["## Reading the step entries {#ref_step_entries}", "", self.note("section.step_entries"), ""]
        out += ["## Shared motion settings {#ref_motion_settings}", "", "[edition: Lite and Pro]", ""]
        out.append(self.note("section.motion_settings") + "\n")
        motion = self.editable_props("UFeelStep_ShapedMotion", own_only=True)
        out.append(self.prop_table("UFeelStep_ShapedMotion", motion))
        out.append("")
        shape_enum = self.types["EFeelMotionShape"]
        out.append("Shapes:")
        out.append("")
        for v in shape_enum.values:
            out.append(f"- **{v.label}**: {sentence(v.doc)}")
        out.append("")
        shaped = [c for c in self.step_classes() if self.is_a(c, "UFeelStep_ShapedMotion")]
        rows = []
        for c in shaped:
            raw = self.ctor_value(c, "Shape") or "EFeelMotionShape::Spring"
            rows.append([f"[name: step_{self.slug(self.types[c].label)}]", self.enum_label(shape_enum, raw.split("::")[-1])])
        out.append("Default shape of each step that uses these settings:")
        out.append("")
        out.append(self.table(["Step", "Default shape"], rows, [50, 50]))
        out.append("")

        groups = self.ov["step_groups"]
        for group in groups:
            members = [c for c in self.step_classes() if self.group_of(c) == group["key"]]
            out += [f"## {group['title']} {{#ref_steps_{group['key']}}}", ""]
            gnote = self.note("group." + group["key"])
            if gnote:
                out += [gnote, ""]
            for cls in members:
                out.append(self.step_entry(cls))
        return "\n".join(out).rstrip() + "\n"

    @staticmethod
    def slug(text: str) -> str:
        return re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")

    def group_of(self, cls: str) -> str:
        forced = self.ov.get("step_group_override", {}).get(cls)
        if forced:
            return forced
        tag = self.channel_of(cls)
        for group in self.ov["step_groups"]:
            for prefix in group["channels"]:
                if tag == prefix or tag.startswith(prefix + "."):
                    return group["key"]
        raise SystemExit(f"no step group for {cls} ({tag})")

    def step_entry(self, cls: str) -> str:
        td = self.types[cls]
        label = td.label
        anchor = "step_" + self.slug(label)
        module = td.file.parts[td.file.parts.index("Public") - 1]
        lines = [f"### {label} {{#{anchor}}}", "", f"[edition: {self.edition(cls)}]", ""]
        note = self.note(cls)
        if not note:
            self.warnings.append(f"no behaviour note for {cls}")
        else:
            lines += [note, ""]
        channel = self.channel_of(cls)
        channel_note = self.ov.get("channel_notes", {}).get(cls)
        group = self.comfort_group_of(channel)
        comfort_note = self.ov.get("comfort_notes", {}).get(cls)
        preview = self.inline_or_cpp(cls, "SupportsPreview_Implementation", "true") == "true"
        requires_duration = self.inline_or_cpp(cls, "RequiresDuration", "true") == "true"
        flat = self.inline_or_cpp(cls, "UsesConstantIntensityByDefault", "false") == "true"
        facts = [f"- **Class:** `{cls}`, module {module}."]
        facts.append(f"- **Default channel:** " + (channel_note or f"`{channel}`") + ".")
        facts.append("- **Comfort group:** " + (comfort_note or (group if group else "none, only Master applies")) + ".")
        preview_note = self.ov.get("preview_notes", {}).get(cls)
        facts.append("- **Editor preview:** " + (preview_note or ("yes" if preview else "no, the track shows **No preview**")) + ".")
        facts.append("- **Track length:** " + ("needs a length" if requires_duration else "can be an instant track (length 0)") + ".")
        facts.append("- **New tracks start with:** " + ("a flat intensity curve at 1" if flat else "an intensity curve that fades from 1 to 0") + ".")
        if self.is_a(cls, "UFeelStep_ShapedMotion"):
            raw = self.ctor_value(cls, "Shape") or "EFeelMotionShape::Spring"
            shape = self.enum_label(self.types["EFeelMotionShape"], raw.split("::")[-1])
            facts.append(f"- **Motion shape:** {shape} by default; the shape settings are described in [ref: ref_motion_settings].")
        lines += facts + [""]
        skip = {p.name for p in self.types["UFeelStep_ShapedMotion"].props} if self.is_a(cls, "UFeelStep_ShapedMotion") else set()
        props = self.editable_props(cls, skip)
        if props:
            lines.append(self.prop_table(cls, props))
            lines.append("")
            for block in self.struct_tables(props, cls):
                lines += [block, ""]
        checks = []
        for td2 in self.chain(cls):
            checks += self.facts.validation.get(td2.name, [])
        if checks:
            lines.append("Checks when the recipe is saved:")
            lines.append("")
            for level, text in checks:
                lines.append(f"- {level}: \"{clean_text(text, cls)}\"")
            lines.append("")
        return "\n".join(lines)

    def chapter17(self) -> str:
        out = [GENERATED_MARK, "", "# Blueprint nodes and components {#ch17}", ""]
        out.append(self.note("chapter.17") + "\n")
        for section in self.ov["ch17_sections"]:
            out += [f"## {section['title']} {{#{section['anchor']}}}", ""]
            snote = self.note("section." + section["anchor"])
            if snote:
                out += [snote, ""]
            for item in section.get("items", []):
                out.append(self.ch17_item(item))
        return "\n".join(out).rstrip() + "\n"

    def ch17_item(self, item: dict) -> str:
        kind = item["kind"]
        if kind == "fn":
            cls, name = item["id"].split(".")
            fn = self.find_func(cls, name)
            return self.function_block(fn, f"fn:{cls}.{name}", anchor=item.get("anchor", ""), owner_label=item.get("target", ""), node=item.get("node", ""))
        if kind == "type":
            cls = item["id"]
            td = self.types[cls]
            title = item.get("title") or td.label
            lines = [f"### {title}" + (f" {{#{item['anchor']}}}" if item.get("anchor") else ""), "", f"[edition: {self.edition('type:' + cls)}]", ""]
            lines += self.doc_blocks(td.doc.summary)
            note = self.note("type:" + cls)
            if note:
                lines += [note, ""]
            props = self.editable_props(cls)
            expand = item.get("expand")
            if expand:
                # Structs shown with their inner fields in place (ShowOnlyInnerProperties).
                expanded = []
                for p in props:
                    if p.name == expand:
                        expanded += self.editable_props(p.type.strip())
                    else:
                        expanded.append(p)
                props = expanded
            if props:
                lines.append(self.prop_table(cls, props))
                lines.append("")
                for block in self.struct_tables(props, cls):
                    lines += [block, ""]
            events = [p for p in self.all_props(cls) if "BlueprintAssignable" in p.flags]
            for e in events:
                sig = self.facts.delegates.get(e.type.strip(), [])
                pins = ", ".join(f"**{display_name(n, t == 'bool')}** ({self.pin_type(t)})" for t, n in sig)
                lines.append(f"Event **{e.label}**" + (f" with {pins}" if pins else "") + f": {sentence(e.doc.text())}")
                lines.append("")
            for fname in item.get("functions", []):
                fn = self.find_func(cls, fname)
                lines.append(self.function_block(fn, f"fn:{cls}.{fname}", heading_level="####", owner_label=item.get("target", td.label)))
            return "\n".join(lines)
        if kind == "enum":
            td = self.types[item["id"]]
            lines = [f"{item.get('lead', '')}", ""]
            for v in td.values:
                lines.append(f"- **{v.label}**: {sentence(v.doc)}")
            lines.append("")
            return "\n".join(lines)
        if kind == "native":
            return self.native_block(item)
        if kind == "note":
            return self.note(item["id"]) + "\n"
        raise SystemExit("unknown ch17 item kind " + kind)

    def native_block(self, item: dict) -> str:
        cls = item["id"]
        td = self.types[cls]
        wanted = item["functions"]
        rows = []
        body = td.body
        for name in wanted:
            m = re.search(r"(/\*\*(?:(?!\*/).)*\*/)\s*((?:static\s+)?[\w<>\*&:, ]+?\b" + name + r"\s*\([^;{]*\)\s*(?:const)?)\s*[;{]", body, re.S)
            if not m:
                raise SystemExit(f"native function {cls}::{name} not found")
            doc = parse_doc(m.group(1)[3:-2], cls + "." + name)
            decl = re.sub(r"\s+", " ", m.group(2)).strip()
            rows.append([f"`{decl}`", sentence(doc.text()), self.edition(f"cpp:{cls}.{name}")])
        for name in item.get("delegates", []):
            m = re.search(r"(\w+)\s+" + name + r"\s*;", body)
            dtype = m.group(1)
            src = strip_line_comments(read_source(td.file))
            dm = re.search(r"/\*\*((?:(?!\*/).)*)\*/\s*DECLARE_MULTICAST_DELEGATE_\w+\(\s*" + dtype + r"\s*,([^;]*)\);", src, re.S)
            doc = parse_doc(dm.group(1), dtype)
            sig = ", ".join(f"{t} {n}" for t, n in self.facts.delegates.get(dtype, []))
            rows.append([f"`{dtype} {name}` ({sig})", sentence(doc.text()), self.edition(f"cpp:{cls}.{name}")])
        return self.table(["Declaration", "What it does", "Edition"], rows, [42, 44, 14]) + "\n"

    def chapter18(self) -> str:
        out = [GENERATED_MARK, "", "# Project settings and editor preferences {#ch18}", ""]
        out.append(self.note("chapter.18") + "\n")
        settings = self.types["UFeelSettings"]
        props = self.editable_props("UFeelSettings")
        for section in self.ov["ch18_sections"]:
            out += [f"## {section['title']} {{#{section['anchor']}}}", ""]
            if section.get("edition"):
                out += [f"[edition: {section['edition']}]", ""]
            snote = self.note("section." + section["anchor"])
            if snote:
                out += [snote, ""]
            cats = section.get("categories")
            if cats:
                group = [p for p in props if p.category in cats]
                out.append(self.prop_table("UFeelSettings", group))
                out.append("")
                for block in self.struct_tables(group, "UFeelSettings"):
                    out += [block, ""]
            special = section.get("special")
            if special == "comfort_scales":
                out.append(self.comfort_scales_tables())
            if special == "channel_groups":
                out.append(self.channel_groups_table())
            if special == "editor":
                eprops = self.editable_props("UFeelEditorSettings")
                out.append(self.prop_table("UFeelEditorSettings", eprops))
                out.append("")
        return "\n".join(out).rstrip() + "\n"

    def comfort_scales_tables(self) -> str:
        scales = self.editable_props("FFeelComfortScales")
        ctor = self.types["UFeelSettings"].ctor
        presets = [("DefaultComfortScales", "Default"), ("ReducedMotionPreset", "Reduced Motion"),
                   ("ReducedFlashingPreset", "Reduced Flashing"), ("NoHapticsPreset", "No Haptics")]
        lines = ["Fields of a set of comfort scales (used by **Default Comfort Scales**, the three presets and custom Feel Comfort Preset assets):", ""]
        lines.append(self.prop_table("FFeelComfortScales", scales))
        lines.append("")
        lines.append("Values of the presets as FeelKit ships them. Each preset replaces all fields at once, so a field a preset does not change keeps the value shown in the Default column.")
        lines.append("")
        rows = []
        for p in scales:
            row = [f"**{p.label}**"]
            for key, _ in presets:
                raw = ctor.get(f"{key}.{p.name}", p.default)
                row.append(self.with_units(self.format_value(p.type, raw, "FFeelComfortScales", p.name), self.units(p, "FFeelComfortScales")))
            rows.append(row)
        lines.append(self.table(["Field"] + [label for _, label in presets], rows, [32, 17, 17, 17, 17]))
        lines.append("")
        return "\n".join(lines)

    def channel_groups_table(self) -> str:
        rows = [[f"`{c}`", g] for c, g in self.default_channel_groups()]
        mapped = {c for c, _ in self.default_channel_groups()}
        unmapped = [t for _, (t, _) in sorted(self.facts.tags.items(), key=lambda kv: kv[1][0])
                    if t.startswith("Feel.") and not t.startswith(("Feel.Feeling", "Feel.Genre", "Feel.Event")) and not any(t == m or t.startswith(m + ".") for m in mapped)]
        lines = ["Default **Channel Comfort Groups**:", "", self.table(["Channel", "Comfort group"], rows, [55, 45]), ""]
        lines.append("Channels with no entry are scaled by Master only: " + ", ".join(f"`{t}`" for t in unmapped) + ".")
        lines.append("")
        return "\n".join(lines)

    def chapter19(self) -> str:
        out = [GENERATED_MARK, "", "# Console commands {#ch19}", ""]
        out.append(self.note("chapter.19") + "\n")
        rows = []
        for name, vtype, default, help_text in self.facts.cvars:
            value = self.number(default) if vtype == "float" else ("1" if default == "true" else "0" if default == "false" else default)
            rows.append([f"`{name}`", value, sentence(clean_text(help_text, name)), self.edition("cvar:" + name)])
        stat_group = next((n for k, n in self.facts.stats if k == "STATS_GROUP"), "")
        rows.append([f"`stat {stat_group}`", "", "Shows FeelKit's own stat counters (see below).", self.edition("cmd:stat")])
        rows.append([f"`showdebug {self.facts.showdebug_category.lower()}`", "", "Draws what FeelKit is doing on the game view (see below).", self.edition("cmd:showdebug")])
        out.append(self.table(["Command", "Default", "What it does", "Edition"], rows, [22, 10, 54, 14]))
        out.append("")
        for name, vtype, default, help_text in self.facts.cvars:
            anchor = "con_" + self.slug(name)
            out += [f"## {name} {{#{anchor}}}", "", f"[edition: {self.edition('cvar:' + name)}]", "", self.note("cvar:" + name), ""]
        out += [f"## stat {stat_group} {{#con_stat_feel}}", "", f"[edition: {self.edition('cmd:stat')}]", ""]
        counters = [n for k, n in self.facts.stats if k != "STATS_GROUP"]
        out.append(self.note("cmd:stat").replace("{COUNTERS}", " and ".join(f"**{c}**" for c in counters)))
        out.append("")
        out += [f"## showdebug {self.facts.showdebug_category.lower()} {{#con_showdebug_feel}}", "", f"[edition: {self.edition('cmd:showdebug')}]", "", self.note("cmd:showdebug"), ""]
        return "\n".join(out).rstrip() + "\n"


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(description="Write the generated reference chapters of the FeelKit Manual.")
    parser.add_argument("--plugin", type=Path, default=DEFAULT_PLUGIN, help="FeelKit plugin folder")
    args = parser.parse_args()
    if not (args.plugin / "FeelKit.uplugin").exists():
        print(f"FeelKit.uplugin not found in {args.plugin}", file=sys.stderr)
        return 1
    overrides = yaml.safe_load((HERE / "overrides.yaml").read_text(encoding="utf-8"))
    ref = Reference(args.plugin, overrides)
    try:
        ref.load()
        chapters = {
            "16_steps.generated.md": ref.chapter16(),
            "17_nodes.generated.md": ref.chapter17(),
            "18_settings.generated.md": ref.chapter18(),
            "19_console.generated.md": ref.chapter19(),
        }
    except CodeLeak as error:
        print(f"Stopped: {error}", file=sys.stderr)
        return 1
    for name, text in chapters.items():
        if CODE_RE.search(text):
            print(f"Stopped: internal code in {name}: {CODE_RE.search(text).group(0)}", file=sys.stderr)
            return 1
        (SRC / name).write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote src/{name}")
    for w in sorted(set(ref.warnings)):
        print("warning:", w)
    for key in sorted(set(ref.unassigned_editions)):
        print("edition not listed in overrides.yaml, marked Pro:", key)
    return 0


if __name__ == "__main__":
    sys.exit(main())
